development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: saroj
  password:

 production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username: saroj
  password:

