# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://jashkenas.github.com/coffee-script/
jQuery  ->
   $('#himalaya_datepicker').datepicker(
     altField:"#himalaya",
     dateFormat: "yy-mm-dd",
     minDate: -0,
     dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','S&aacute;'],
     maxDate: "+1M +10D");

   $.ajaxSetup({ cache: false });

#$(document).ready ->
  #$(".owl-carousel").owlCarousel
    #navigation: true
    #autoPlay: 4000 #Set AutoPlay to 3 seconds
    #paginationSpeed: 4000
    #singleItem: true

  #return

  #$.ajaxSetup({ cache: false });

  $(document).ready ->
    $(document).mousemove (e) ->
      $('#exitpopup').css 'left', window.innerWidth / 2 - ($('#exitpopup').width() / 2)
      $('#exitpopup').css 'top', window.innerHeight / 2 - ($('#exitpopup').height() / 2)
      $('#saroj').css 'left', window.innerWidth / 2 - ($('#saroj').width() / 2)
      $('#saroj').css 'top', window.innerHeight / 2 - ($('#saroj').height() / 2)
      if e.pageY <= 5
        # Show the exit popup
        $('#exitpopup_bg').fadeIn()
        $('#exitpopup').fadeIn()
      return
    $('#closebutton').click ->
      $('#exitpopup_bg').fadeOut()
      $('#exitpopup').slideUp()
      return

  # 'input[type="submit"]'
  # generated by js2coffee 2.0.1


  $(document).ready ->
    n = '#nav'
    $('#nav-menu').click ->
      if $(n).hasClass('nav-open')
        $(n).removeClass 'nav-open'
      else
        $(n).addClass 'nav-open'
      return
    return
